### ISSUE TITLE
google.api_core.exceptions.InvalidArgument: 400 One or more TimeSeries could not be written: Points must be written in order. One or more of the points specified had an older end time than the most recent point.: timeSeries[0]

### ISSUE THREAD

**Issue by naman-noon1** [googleapis/python-monitoring#57]
These are the points (In the order i am pushing to google cloud monitor):
1. points {
  interval {
    end_time {
      seconds: 1602230436
    }
  }

2. points {
  interval {
    end_time {
      seconds: 1602230437
    }
  }

3. points {
  interval {
    end_time {
      seconds: 1602230438
    }
  }

4. points {
  interval {
    end_time {
      seconds: 1602230438
    }
  }

5. points {
  interval {
    end_time {
      seconds: 1602230439
    }
  }

6. points {
  interval {
    end_time {
      seconds: 1602230487
    }
  }

7. points {
  interval {
    end_time {
      seconds: 1602230498
    }
  }

Is it because i am pushing two points with same end time?
Please suggest the solution as well.

**Comment by meredithslota** [comment]
A similar question was answered here: https://stackoverflow.com/questions/60996028/bigquery-cloud-monitoring-api-400-one-or-more-timeseries-could-not-be-written I do think that duplicate entries might not be allowed and that's why you're getting this error. The suggested answer does have a proposed solution but it depends on how you're generating those points (e.g. if you are getting the points another way, that solution may not work). If you are still seeing this, can you please file a new issue and also describe how you're generating the points?
