### ISSUE TITLE
Realistic examples (aggregation)

### ISSUE THREAD

**Issue by leigh-johnson** [googleapis/python-monitoring#78]
Hey y'all,

I'm having a hard time translating metrics queries into Python API usage. Can y'all make any recommendations? 

For example, I have this query which reports the oldest unack'd message age in a PubSub subscription, sampled every minute.
```
fetch pubsub_subscription
| metric 'pubsub.googleapis.com/subscription/oldest_unacked_message_age'
| filter
    resource.project_id == '443684903852'
    && (resource.subscription_id == 'octoprint-events-webapp-prod')
| group_by 1m,
    [value_oldest_unacked_message_age_mean:
       max(value.oldest_unacked_message_age)]
| every 1m
```

When I try to to compose queries with the Python API, the resulting pandas Dataframe is always empty. Are there any examples of how I'm supposed to use this library?

Here's an example:
```python
import logging
from google.cloud import monitoring_v3
from django.conf import settings
logger = logging.getLogger(__name__)
client = monitoring_v3.MetricServiceClient()
result = query.Query(
    client,
    settings.GCP_PROJECT_ID,
    'pubsub.googleapis.com/subscription/oldest_unacked_message_age', 
    minutes=10
).as_dataframe()
logger.info(f'***** {result}')
```
```
django             | INFO 2021-01-10 14:57:26,916 healthcheck 2714 139732496103168 ***** Empty DataFrame
django             | Columns: []
django             | Index: []
django             | INFO:     
```

Thanks!
Leigh

**Comment by busunkim96** [comment]
Hi @leigh-johnson,

The full list of monitoring samples is at https://cloud.google.com/monitoring/docs/samples

Are any of those helpful for what you're trying to do?

**Comment by denverdigiman** [comment]
Hi @busunkim96,
For me, the link to the samples helped me out, so thank you, for pointing out the link to the samples.

I was having issues figuring out how to use list_time_series, so I followed the steps outlined in Read Metric Data sample (https://cloud.google.com/monitoring/docs/samples/monitoring-read-timeseries-simple), and with a bit of modification, I was able to get the most-recent interval sample for the metric I am trying to get data on (storage.googleapis.com/storage/total_bytes)

What I can't figure out now, is, how to access the values in the returned ListTimeSeriesPager object 'results', which appears to be a ListTimeSeries Type. I do see that I can access the Points object of the 'results'. object, but I do not see how to get to the values within the Points object.

For example, in the below output, I want to access the value object, so that I can retrieve the actual value (69506018.0)

```
metric_kind: GAUGE
value_type: DOUBLE
points {
  interval {
    start_time {
      seconds: 1611380400
    }
    end_time {
      seconds: 1611380400
    }
  }
  value {
    double_value: 69506018.0
  }
```

**Comment by arindamchoudhury** [comment]
Code snippet I use to run MQL query:
```python
from google.cloud.monitoring_v3.services.query_service import QueryServiceClient
from google.cloud.monitoring_v3.types import metric_service

metric_query = metric_service.QueryTimeSeriesRequest(name=project_name, query=query)
results = self.client.query_time_series(metric_query)
```

**Comment by meredithslota** [comment]
The samples have migrated to this repo: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/monitoring and are still all available at https://cloud.google.com/monitoring/docs/samples. For any new sample requests, please use the `python-docs-samples` repo. Thanks!
